version: '3'
services:

  web:
    container_name: web
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: gunicorn blogProject.wsgi:application --bind 0.0.0.0:8001
    environment:
      DJANGO_SETTINGS_MODULE: blogProject.settings.prod
    env_file:
      - .env
    volumes:
      - static:/home/app/web/static
      - media:/home/app/web/media
    expose:
      - 8001
    entrypoint:
      - sh
      - config/docker/entrypoint.prod.sh 

  nginx:
    container_name: nginx
    build: ./config/nginx
    volumes:
      - static:/home/app/web/static
      - media:/home/app/web/media
    ports:
      - "80:80"
    depends_on:
      - web
    environment:
      TZ: "Asia/Seoul"

volumes:
  static:
  media:
